module.exports = [
  { id: 157, sigla: 'MDR', grupo: 'AL: PARTICULAR', nome: 'MEDRADIUS', cnpj: '03.866.223/0001-24', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 241, sigla: 'UFA', grupo: 'AL: PÚBLICO', nome: 'HOSPITAL UNIVERSITÁRIO PROFESSOR ALBERTO ANTUNES – HUPAA', cnpj: '15.126.437/0020-06', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 153, sigla: 'HDR', grupo: 'AM: PARTICULAR', nome: 'OZN HEALTH SPE S.A. (HOSPITAL DELPHINA RINALDI)', cnpj: '18.080.368/0001-72', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'H' },
  { id: 232, sigla: 'UCS', grupo: 'AM: PUBLICO', nome: 'UPA CAMPOS SALLES', cnpj: '23.453.830/0004-12', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'H' },
  { id: 88, sigla: 'AMB', grupo: 'BA: IMIP', nome: 'HOSPITAL ARISTIDES MALTEZ', cnpj: '15.180.967/0001-00', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 128, sigla: 'APH', grupo: 'BA: PARTICULAR', nome: 'CENTRO MÉDICO HOSPITALAR AGENOR PAIVA', cnpj: '01.442.539/0001-63', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 252, sigla: 'HOE', grupo: 'BA: PARTICULAR', nome: 'HOEB - HOSPITAL ORTOPÉDICO DO ESTADO DA BAHIA', cnpj: '60.765.823/0083-86', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 223, sigla: 'CAL', grupo: 'BA: PROSAUDE', nome: 'HOSPITAL DAS CLÍNICAS DE ALAGOINHAS', cnpj: '13.519.634/0001-82', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 177, sigla: 'SPD', grupo: 'CE: PARTICULAR', nome: 'POLICLÍNICA PASSARÉ E POLICLÍNICA BONSUCESSO', cnpj: '', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 247, sigla: 'PNT', grupo: 'CE: PARTICULAR', nome: 'SUPORTE NUTRICIONAL E QUIMIOTERAPIA LTDA', cnpj: '01.873.957/0003-77', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 175, sigla: 'HGF', grupo: 'CE: PÚBLICO', nome: 'HOSPITAL GERAL DE FORTALEZA-HGF', cnpj: '07.954.571/0014-29', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 14, sigla: 'HUF', grupo: 'CE: UNIMED', nome: 'UNIMED FORTALEZA', cnpj: '05.868.278/0002-80', responsavel: 'RODRIGO LOPES PEREIRA COSTA', carteira: 'C' },
  { id: 220, sigla: 'HOM', grupo: 'DF: GRUPO D\'OR', nome: 'HOME- HOSPITAL ORTOPÉDICO E MEDICINA ESPECIALIZADA LTDA', cnpj: '37.108.388/0001-59', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'G' },
  { id: 197, sigla: 'FAV', grupo: 'EBEM', nome: 'FUNDAÇÃO ALTINO VENTURA', cnpj: '10.667.814/0001-38', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 196, sigla: 'HSM', grupo: 'EBEM', nome: 'GRUPO SANTA MARTA', cnpj: '00.610.980/0001-44', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'G' },
  { id: 188, sigla: 'HAM', grupo: 'EBEM', nome: 'HOSPITAL AGAMENON MAGALHÃES', cnpj: '10.572.048/0003-90', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 198, sigla: 'HAR', grupo: 'EBEM', nome: 'HOSPITAL DA AERONÁUTICA DO RECIFE', cnpj: '', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 200, sigla: 'HUB', grupo: 'EBEM', nome: 'HOSPITAL UNIVERSITÁRIO DE BRASÍLIA', cnpj: '', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'G' },
  { id: 199, sigla: 'IMB', grupo: 'EBEM', nome: 'IMAGENS MÉDICAS BRASÍLIA', cnpj: '', responsavel: 'SEM RESPONSAVEL', carteira: 'sem carteira' },
  { id: 244, sigla: 'HPL', grupo: 'ES: PARTICULAR', nome: 'HOSPITAL DE PLÁSTICA', cnpj: '28.756.228/0001-25', responsavel: 'SEM RESPONSAVEL', carteira: 'sem carteira' },
  { id: 132, sigla: 'HSR', grupo: 'ES: PARTICULAR', nome: 'HOSPITAL SANTA RITA', cnpj: '28.137.925/0001-06', responsavel: 'RAFAELA ALMEIDA MAIA', carteira: 'E' },
  { id: 133, sigla: 'SJH', grupo: 'ES: PARTICULAR', nome: 'HOSPITAL SÃO JOSÉ - COLATINA', cnpj: '27.502.715/0001-07', responsavel: 'RAFAELA ALMEIDA MAIA', carteira: 'E' },
  { id: 25, sigla: 'VAH', grupo: 'ES: PARTICULAR', nome: 'VITÓRIA APART HOSPITAL', cnpj: '02.209.094/0001-39', responsavel: 'RAFAELA ALMEIDA MAIA', carteira: 'E' },
  { id: 217, sigla: 'SCC', grupo: 'ES: PUBLICO', nome: 'SANTA CASA DE MISERICÓRDIA DE COLATINA', cnpj: '13.769.132/0001-24', responsavel: 'RAFAELA ALMEIDA MAIA', carteira: 'E' },
  { id: 60, sigla: 'UNC', grupo: 'ES: UNIMED', nome: 'UNIMED NOROESTE CAPIXABA', cnpj: '39.384.664/0001-37', responsavel: 'RAFAELA ALMEIDA MAIA', carteira: 'E' },
  { id: 20, sigla: 'UVX', grupo: 'ES: UNIMED', nome: 'UNIMED VITÓRIA', cnpj: '27.578.434/0001-20', responsavel: 'RAFAELA ALMEIDA MAIA', carteira: 'E' },
  { id: 143, sigla: 'CCO', grupo: 'ESCRITÓRIO', nome: 'CENTRAL COMPARTILHADA DE OPERAÇÕES', cnpj: '', responsavel: 'VICTOR BEZERRIL DE ARAUJO', carteira: 'sem carteira' },
  { id: 249, sigla: 'CCP', grupo: 'ESCRITÓRIO', nome: 'CENTRAL COMPARTILHADA DE OPERAÇÕES - SP', cnpj: '', responsavel: 'VICTOR BEZERRIL DE ARAUJO', carteira: 'sem carteira' },
  { id: 17, sigla: 'TCS', grupo: 'ESCRITÓRIO', nome: 'TECSAÚDE', cnpj: '03.480.539/0001-83', responsavel: 'SEM RESPONSAVEL', carteira: 'sem carteira' },
  { id: 256, sigla: 'HUG', grupo: 'GO: PARTICULAR', nome: 'HOSPITAL ESTADUAL DE URGÊNCIAS DE GOIÁS DR. VALDEMIRO CRUZ', cnpj: '38.202.078/0001-61', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'G' },
  { id: 236, sigla: 'HMA', grupo: 'GO: PROSAUDE', nome: 'HOSPITAL MUNICIPAL DE APARECIDA DE GOIÂNIA', cnpj: '', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'G' },
  { id: 181, sigla: 'HMM', grupo: 'MA: PARTICULAR', nome: 'HOSPITAL MARANHENSE', cnpj: '06.265.912/0001-71', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'F' },
  { id: 209, sigla: 'SMI', grupo: 'MA: PARTICULAR', nome: 'HOSPITAL SANTA MÔNICA DE IMPERATRIZ', cnpj: '23.430.770/0001-70', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'F' },
  { id: 172, sigla: 'UIM', grupo: 'MA: PARTICULAR', nome: 'UNIMED IMPERATRIZ DO MARANHÃO', cnpj: '07.057.185/0002-09', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'F' },
  { id: 259, sigla: 'UFT', grupo: 'MG: PÚBLICO', nome: 'HOSPITAL DAS CLINICAS - UFTM', cnpj: '25.437.484/0002-42', responsavel: 'RAFAELA ALMEIDA MAIA', carteira: 'C' },
  { id: 260, sigla: 'DTQ', grupo: 'NOVO GRUPO DE EMPRESAS', nome: 'GESTÃO DA QUALIDADE - DTQ', cnpj: '', responsavel: 'SEM RESPONSAVEL', carteira: 'sem carteira' },
  { id: 179, sigla: 'CHP', grupo: 'PA: PÚBLICO', nome: 'COMPLEXO HOSPITALAR UNIVERSITARIO DA UFPA', cnpj: '15.126.437/0037-54', responsavel: 'SEM RESPONSAVEL', carteira: 'H' },
  { id: 127, sigla: 'HSM', grupo: 'PA:INDSH', nome: 'DIAGNOSIS CENTRO DE DIAGNOSTICOS LTDA - HSM', cnpj: '63.789.381/0001-40', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'H' },
  { id: 38, sigla: 'HRM', grupo: 'PA:INDSH', nome: 'HOSPITAL REGIONAL PUBLICO DO MARAJÓ', cnpj: '05.054.929/0001-17', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'H' },
  { id: 215, sigla: 'RPC', grupo: 'PA:INDSH', nome: 'HOSPITAL REGIONAL PÚBLICO DOS CAETÉS', cnpj: '', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'H' },
  { id: 95, sigla: 'UJP', grupo: 'PB: UNIMED', nome: 'UNIMED JOÃO PESSOA COOPERATIVA DE TRABALHO MÉDICO', cnpj: '08.680.639/0003-39', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 18, sigla: 'IMP', grupo: 'PE: IMIP', nome: 'IMIP - INSTITUTO DE MEDICINA INTEGRAL PROF. FERNANDO FIGUEIRA', cnpj: '10.988.301/0001-29', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 70, sigla: 'IUP', grupo: 'PE: IMIP', nome: 'UPAE', cnpj: '', responsavel: 'SEM RESPONSAVEL', carteira: 'sem carteira' },
  { id: 69, sigla: 'IUG', grupo: 'PE: IMIP', nome: 'UPAE GARANHUNS', cnpj: '', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'F' },
  { id: 10, sigla: 'HAS', grupo: 'PE: PARTICULAR', nome: 'CENTRO HOSPITALAR ALBERT SABIN', cnpj: '09.866.294/0001-03', responsavel: 'RODRIGO LOPES PEREIRA COSTA', carteira: 'B' },
  { id: 160, sigla: 'HCP', grupo: 'PE: PARTICULAR', nome: 'HOSPITAL DE CÂNCER DE PERNAMBUCO', cnpj: '10.894.988/0001-33', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 161, sigla: 'PTR', grupo: 'PE: PARTICULAR', nome: 'HOSPITAL MED IMAGEM', cnpj: '63.326.243/0002-15', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'F' },
  { id: 242, sigla: 'TEC', grupo: 'PE: PARTICULAR', nome: 'TECSAÚDE LOCAÇÃO', cnpj: '06.889.652/0001-05', responsavel: 'SEM RESPONSAVEL', carteira: 'sem carteira' },
  { id: 167, sigla: 'NTC', grupo: 'PE: PÚBLICO', nome: 'APOIO NEOVERO E TECSAÚDE CONTRA A COVID-19', cnpj: '', responsavel: 'SEM RESPONSAVEL' },
  { id: 100, sigla: 'RHM', grupo: 'PE: PÚBLICO', nome: 'HCP GESTÃO', cnpj: '10.894.988/0004-86', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'sem carteira' },
  { id: 8, sigla: 'HMP', grupo: 'PE: PÚBLICO', nome: 'HEMOPE', cnpj: '10.564.953/0001-36', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 139, sigla: 'HRE', grupo: 'PE: PÚBLICO', nome: 'HOSPITAL DA RESTAURAÇÃO GOV. PAULO GUERRA', cnpj: '10.572.048/0002-09', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 158, sigla: 'HOC', grupo: 'PE: PÚBLICO', nome: 'HOSPITAL UNIVERSITÁRIO OSWALDO CRUZ', cnpj: '11.022.597/0013-25', responsavel: 'RODRIGO JOHNSON GUERRA BEZERRA', carteira: 'D' },
  { id: 159, sigla: 'HMI', grupo: 'PE: UNIMED', nome: 'HOSPITAL GERAL MATERNO INFANTIL - UNIMED RECIFE', cnpj: '', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 11, sigla: 'HUR', grupo: 'PE: UNIMED', nome: 'HOSPITAL UNIMED RECIFE', cnpj: '11.214.624/0019-57', responsavel: 'FELIX JERONIMO DE ARAUJO NETO', carteira: 'B' },
  { id: 115, sigla: 'HTC', grupo: 'RJ: PARTICULAR', nome: 'HOSPITAL DAS CLÍNICAS DE TERESÓPOLIS COSTANTINO OTTAVIANO', cnpj: '32.190.092/0001-06', responsavel: 'VICTOR BEZERRIL DE ARAUJO', carteira: 'C' },
  { id: 254, sigla: 'HCN', grupo: 'RN: PARTICULAR', nome: 'HOSPITAL DO CORACAO DE NATAL', cnpj: '26.753.292/0002-08', responsavel: 'WAGNER TORRES RUFINO DO AMARAL', carteira: 'F' },
  { id: 180, sigla: 'MSP', grupo: 'SP: PARTICULAR', nome: 'HOSPITAL MILITAR DE ÁREA DE SÃO PAULO', cnpj: '09.591.608/0001-02', responsavel: 'RODRIGO LOPES PEREIRA COSTA', carteira: 'C' },
  { id: 113, sigla: 'ASP', grupo: 'SP: PARTICULAR', nome: 'INSTITUIÇÃO PAULISTA ADVENTISTA DE EDUCAÇÃO E ASSISTÊNCIA SOCIAL', cnpj: '43.586.122/0001-14', responsavel: 'RODRIGO LOPES PEREIRA COSTA', carteira: 'C' },
  { id: 168, sigla: 'PET', grupo: 'SP: PARTICULAR', nome: 'PET CARE', cnpj: '20.049.161/0001-87', responsavel: 'VICTOR BEZERRIL DE ARAUJO', carteira: 'C' },
  { id: 105, sigla: 'UPA', grupo: 'SP: PÚBLICO', nome: 'UPA\'S SÃO PAULO', cnpj: '', responsavel: 'SEM RESPONSAVEL', carteira: 'sem carteira' },
];